server:
  is_update: false
  name: ""
  net: 2
  http_server_addr: ":"
  min_deposit_amount: "30"
  pay_server_address: ""
  remote_sign_api_url: ""
  tx_fee_rate: 1

db:
  mysql:
    addr: "" # 172.17.0.1: docker 182.17.0.1: docker-compose
    user: ""
    password: ""
    db_name: "mybtckb"
    max_open_conn: 100
    max_idle_conn: 50
  redis:
    addr: "127.0.0.1:6379" # 172.17.0.1: docker 182.17.0.1: docker-compose
    password: ""
    db_num: 0
chain:
  ckb:
    url: "https://testnet.ckb.dev"
    index_url: "https://testnet.ckb.dev"
    current_block_number: 13418613 # testnet2 11195338 13,464,897
    confirm_num: 4
    concurrency_num: 100
    privateKey: ""

